### PR TITLE
Allow env var to specify Joker executable to run, and give more info

### PR DESCRIPTION
**Pull request by jcburley**
Also set nonzero exit code for `(wrong exit code)` case.

### CODE REVIEW

**Comment by candid82** [comment]
I am not sure I understand the use case for `JOKER_EXE`. Don't we want to always use `joker` binary from `joker` project directory (which is supposedly the latest built version) to run tests against?

**Comment by jcburley** [comment]
I like to do A/B testing in context of the environment when confused by test results or behavior. Now that I've got a better sense of what that script is doing, and understand build procedures better, it seems less necessary. Though I personally try to avoid baking assumptions (like where executables live) into script balls of mud, this one doesn't belong to that category.

Even outputting the result seems less important now that I've seen it a few times and figured out that the error output is already being shown.

Is it wrong to ensure a nonzero result code is returned for that (when...) block though, I wonder?



On September 15, 2018 11:48:17 AM EDT, Roman Bataev <notifications@github.com> wrote:
>I am not sure I understand the use case for `JOKER_EXE`. Don't we want
>to always use `joker` binary from `joker` project directory (which is
>supposedly the latest built version) to run tests against? 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/candid82/joker/pull/90#issuecomment-421589692

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by candid82** [comment]
I think the addition of `(var-set #'exit-code 1)` line is a valid fix.

**Comment by jcburley** [comment]
Took a few moments to clarify the diagnostics and remove the `JOKER_EXE` override (but still moving determining the executable name to outside the loop, for clarity more than anything).

**Comment by candid82** [comment]
Thanks!

**Pull request merged**
