### PR TITLE
Allow Symbol/Keyword Lexemes a la Clojure

### PR DESCRIPTION
**Pull request by jcburley**
Fixes https://github.com/candid82/joker/issues/447, except for the non-breaking-space exceptions described therein.

### CODE REVIEW

**Comment by jcburley** [comment]
Should I add a comment to the `case` statement in `isSymbolRune` explaining that a few whitespace characters (as well as comma), which could be left to the fallthrough case, are listed in a quest for a bit of extra speed, as they're so common in source code?

**Comment by jcburley** [comment]
Short of writing a Clojure (or Java) program enumerating all of the Unicode points along with their corresponding Character.isWhitespace() predicates, and comparing that to what the new `isJavaSpace()` function does, this is about as close as we need to get for now.

**Comment by candid82** [comment]
> Should I add a comment to the `case` statement in `isSymbolRune` explaining that a few whitespace characters (as well as comma), which could be left to the fallthrough case, are listed in a quest for a bit of extra speed, as they're so common in source code?

Yes, I think a comment would not hurt. Then it will be good to go. Thank you for being so thorough in handling this!

**Comment by jcburley** [comment]
Okay, that should do it for now. I might return to this (and write Clojure/Java and Joker/Go programs to each summarize which runs are whitespace) down the road, but I think it's more urgent to get in the linter improvements next.

**Comment by candid82** [comment]
Looks great, thank you!

**Pull request merged**
