### PR TITLE
Add joker.core/go-spew private function

### PR DESCRIPTION
**Pull request by jcburley**
This has proven to be invaluable in debugging certain aspects of Joker internals. It's not intended for use by Joker users.

### CODE REVIEW

**Comment by candid82** [comment]
While I can appreciate the convenience of having such function, I am not 100% convinced it's valuable enough to justify additional dependency or a lot of additional code.  Do you think it could be conditionally compiled only with specific build tag (similar to what's done for plan9)? That way folks who need it could still get it, but default build would not include this code or the dependency...

**Comment by jcburley** [comment]
> While I can appreciate the convenience of having such function, I am not 100% convinced it's valuable enough to justify additional dependency or a lot of additional code. Do you think it could be conditionally compiled only with specific build tag (similar to what's done for plan9)? That way folks who need it could still get it, but default build would not include this code or the dependency...

Cool idea, I'll look into doing just that!

**Comment by jcburley** [comment]
Ready to go!

**Comment by jcburley** [comment]
Really truly ready to go!

Although, arguably the config map (or nil) should be the first argument, and thing(s) to be dumped would come after that...if this was a public function, I'd be more concerned about getting something like this right the first time. But let me know if you want that change made.

**Comment by candid82** [comment]
I think it's good as is. Thanks a lot!

**Pull request merged**
