### PR TITLE
Fix build error due to shadowed variable

### PR DESCRIPTION
**Pull request by jcburley**
Fixes: https://github.com/candid82/joker/issues/94

### CODE REVIEW

**Comment by candid82** [comment]
Hm... For some reason I am not getting this error. CI build is also passing... I wonder if we use different versions of `vet`. What's the output of `go tool vet -V` on your machine?

**Comment by jcburley** [comment]
```
vet version go1.11
```

(I upgraded to Go 1.11 last night on my main Ubuntu development machine after installing it on my Ubuntu server; already had it on my OS X laptop.)

**Comment by jcburley** [comment]
Also I later noted that some earlier code, in the same file, used `headers` in a similar situation where I'm using `hs`, so if you want to change that for consistency, that might make sense. (I could do it too, but am up against a hard deadline early tomorrow morning, resuming sketchy availability all this coming week.)

**Comment by candid82** [comment]
I'll merge and change it to `headers` since it makes sense for consistency. Still not sure what's causing the discrepancy in `vet` behavior though...

**Pull request merged**
