### PR TITLE
Split out []byte-array generation for core-library namespaces

### PR DESCRIPTION
**Pull request by jcburley**
This eliminates the need to hand-maintain the declaration of the `[]byte` arrays, allowing `gen_data.go` to automatically generate those declarations and initialization (statically, in a func init(), or in a lazily-called function) as it sees fit. `internalLibs` would be empty for `gen_data`, but that seems appropriate, and it works fine.

Something like this might be a next step towards addressing https://github.com/candid82/joker/issues/326 and/or https://github.com/candid82/joker/issues/344.

(`data.go` might be a better name than `procs_data.go`?)

### CODE REVIEW

**Comment by candid82** [comment]
> (data.go might be a better name than procs_data.go?)

Not sure... I am not even sure it's worth creating a separate file for those functions...Granted `procs.go` has become a kitchen sink but I am not sure if many small files are necessarily better. What do you think?

**Comment by candid82** [comment]
I guess `procs_data.go` would be excluded in fast_init build? In that case it does make sense to have it as a separate file...

**Comment by jcburley** [comment]
> I guess `procs_data.go` would be excluded in fast_init build? In that case it does make sense to have it as a separate file...

Actually, it's excluded when building/running `gen_data` -- that's what drove moving that stuff there. Else there'd be conflicts.

I think I prefer the name `data.go` for it though.

**Comment by candid82** [comment]
I saw that it's excluded in `gen_data` build, but I did not realize it was *necessary* to exclude it. What conflicts would it cause?

**Comment by jcburley** [comment]
> I saw that it's excluded in `gen_data` build, but I did not realize it was _necessary_ to exclude it. What conflicts would it cause?

"Conflicts" was the wrong word, actually.

Since `gen_data` generates the _declarations_ of `[]byte` vars, the code in `data.go` won't build until `gen_data` has run.

This might seem a bit strange for now, but I've got another PR following it up that removes all but the references to the linter `[]byte` vars from `data.go`.

**Comment by candid82** [comment]
Ah, that makes sense. Thanks!

**Pull request merged**
