### PR TITLE
Also return integer exit code from joker.os/sh (and sh-from)

### PR DESCRIPTION
**Pull request by jcburley**
This fixes:

https://github.com/candid82/joker/issues/99

However, it also updates re-generated files, which I'm not sure is properly included in this PR.

Please advise.

### CODE REVIEW

**Comment by candid82** [comment]
Hey James, I am on vacation away from computers. I’ll review / merge this PR in about a week. Thank you for your contributions!

**Comment by jcburley** [comment]
No rush -- enjoy your vacation!

**Comment by candid82** [comment]
This looks great, thank you! I usually update (re-generate) the docs before releasing, but sometimes I forget. The only downside of re-generating the docs with the code changes is that [standard library reference](https://candid82.github.io/joker/) will reflect master rather than latest released version. Given current adoption (which I suspect is close to non-existent outside of linting) this should not be a problem at the moment.

**Comment by jcburley** [comment]
Great -- I'll refrain from re-gen'ing the docs in the future. I looked for some kind of master script that ran all the re-gen scripts, but didn't notice one in the repo. Maybe one named `prepare-release` or something like that would be good, and/or have the auto-gen'ed stuff comment whether they're release-generated or build-time-generated? Not sure what is best here....

Meanwhile, my 2nd Joker script is now in production on my server as of several hours ago, and working quite well. Overall it's so much simpler than the Bash script(s) it's replacing...but still fairly simple stuff.

**Comment by candid82** [comment]
There is a script for preparing releases called release.joke and I [just added](https://github.com/candid82/joker/commit/602fc0724b78268e640f723b9ab1f8496604ccc8) the code to regenerate docs to it. Thanks for the suggestion!

**Pull request merged**
