### PR TITLE
Add fast (empty) receiver and rename core/ files *_init.go to *_slow_…

### PR DESCRIPTION
**Pull request by jcburley**
…`*_slow_init.go`.

This leaves Joker with no `*_init.go` files that are not either `*_slow_init.go` or `*_fast_init.go` (and the latter are always tagged accordingly, while the former are when it's necessary to exclude them for the fast builds that the `gen-code` branch, a PR yet to come, supports).

### CODE REVIEW

**Comment by candid82** [comment]
Oops, conflicts...

**Comment by jcburley** [comment]
Will fix now.

**Comment by jcburley** [comment]
Fixed!

**Comment by candid82** [comment]
Thanks!

**Pull request merged**
