### PR TITLE
Support joker.os/chdir

### PR DESCRIPTION
**Pull request by jcburley**
(Not sure that `MakeError()` is quite right for the long term.)

### CODE REVIEW

**Comment by candid82** [comment]
The route I've chosen for error handling is to throw exceptions. Here is an [example](https://github.com/candid82/joker/blob/master/std/url/url_native.go#L9-L16). Might not be the best choice, but it's better to keep it consistent.

**Comment by jcburley** [comment]
> The route I've chosen for error handling is to throw exceptions. Here is an [example](https://github.com/candid82/joker/blob/master/std/url/url_native.go#L9-L16). Might not be the best choice, but it's better to keep it consistent.

I was about to copy that approach, but thought maybe for `os.Chdir` a "not found" might be, well, less than exceptional.

For now, though, I'll bring it into line with everything else. Might be worth revisiting if native Go types (like `error`) are ever surfaced to Joker code....

**Comment by jcburley** [comment]
Hmm, but what would it return as a value if not an error object? For now I'll have it always return `NIL`.

**Comment by candid82** [comment]
Thanks!

**Pull request merged**
